[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# allow scripts/tests to read deployment/network metadata
fs_permissions = [
	{ access = "read", path = "./network" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
